### ISSUE TITLE
Bitcoin Classic warning after resuming from suspend (S3)

### ISSUE THREAD

**Issue by DanielFragaBR** [bitcoinclassic/bitcoinclassic#148]
I'm using Bitcoin Classic v0.12.0cl1 on Linux and when I wake up the system from S3 (suspend), Bitcoin Classic gives me the warning:

```
WARNING: check your network connection, 0 blocks received in the last 4 hours (24 expected)
```

But the blocks are downloaded without problems and the warning remains displayed.

Ps: with Bitcoin Core it doesn't happen.

**Comment by yamamushi** [comment]
~~@DanielFragaBR Could you provide a few pieces of information so that I can try testing this myself through AWS?~~

~~\- Linux Distro (AMI #)~~
~~\- Security Group Ports Opened~~

This appears related to https://github.com/bitcoin/bitcoin/issues/6251 , however I'd like to run tests myself to try and reproduce the issue for debugging. 

@christophebiocca pointed out you were referring to ACPI not S3 storage.

**Comment by christophebiocca** [comment]
I don't think they mean S3 (Simple Storage Service), but S3 (The ACPI power state).

**Comment by DanielFragaBR** [comment]
Yes, I added a parenthesis to clarify better. S3 = suspend.

**Comment by PartTimeLegend** [comment]
Windows 7 Ultimate. Bitlocker enabled, and restore from hibernate also gives this.

**Comment by C-Otto** [comment]
Same for Debian Linux on multiple machines.

**Comment by zander** [comment]
For now, I suggest exiting your app before sleeping
