### ISSUE TITLE
Restore password solution 

### ISSUE THREAD

**Issue by SartoNess** [bitcoinclassic/bitcoinclassic#150]
Many users do not have acccess to their bitcoins because they have forgotten their password,it would be a good idea to have a option forgot password that will remind us the password ?

**Comment by christophebiocca** [comment]
That cannot exist unfortunately. Web services have a "forgot password" option that let's you _set_ a new password, but usually doesn't tell you your old password (they shouldn't be able to if they did their work properly).

Because the wallet was encrypted, setting a new password doesn't help, the wallet's contents are still irrecoverable.

Generally Bitcoinqt's backup procedures are painful and it isn't recommended for most users for that reason.

**Comment by zander** [comment]
Thanks for the feature request, I don't think this can be done securely so I'll close this one.

Sorry about that.
