### ISSUE TITLE
Warning: This version is obsolete; upgrade required!

### ISSUE THREAD

**Issue by C-Otto** [bitcoinclassic/bitcoinclassic#170]
I guess a new release (merge with Core?) is necessary.

**Comment by C-Otto** [comment]
https://www.reddit.com/r/btc/comments/4kmfhe/classic_node_warning_this_version_is_obsolete/d3g74ok

**Comment by crypto-sporidium** [comment]
Yeah I also got this on. Not sure what its all about. ?   I switched back to core for the moment as I cant find any info on any actual issue here.  core is only 12.01  and also the build is 4 months old so not sure what the deal is ?

**Comment by zander** [comment]
Fixed in the stable branch. https://github.com/bitcoinclassic/bitcoinclassic/commit/f6e014f83ee8714ca169aee0bdbb48da6d162697

**Comment by C-Otto** [comment]
Thank you, but that is a hack not a fix.

**Comment by zander** [comment]
The code is legacy code from a simpler time. A time where BIP9 didn't get used. A time where only hardforks were really used for upgrading the protocol.

In this new time where a lot (up to 28) of different protocol changes can be proposed at the same time, it is a rather difficult proposition on the whole on how to handle any such required upgrades.

For starters, each different bitcoin change has different parameters for acceptance. And it is essentially impossible to determine how far an individual proposal has gotten in an old client because that old client also doesn't know about the activation details.

It is true that there needs to be a better solution for individual node operators to know about changes to the protocol that his client is not aware of. We have some ideas and new code is currently not one of them.

**Comment by holgerkpedersen** [comment]
So, what do we (normal users of the wallet) do to get rid of the warning?

**Comment by C-Otto** [comment]
You use the most recent release.

**Comment by zander** [comment]
@holgerkpedersen see https://github.com/bitcoinclassic/bitcoinclassic/releases

**Comment by holgerkpedersen** [comment]
Upgrade from fully functional 0.12.0cl1: Applying latest bitcoin-qt.exe (0.12.1cl1)

I get an error:
   "Error reading from the database, shutting down. "

Do I really have to "-reindex" all? - Hmm... I'll do it!

**Comment by C-Otto** [comment]
@holgerkpedersen could you open a new issue? This does not seem to be related.

**Comment by zander** [comment]
Not sure what anyone can do about database corruption. That should obviously not happen. 
If you do feel you want to open a new issue, I suggest doing that against bitcoincore as the code is the same and they wrote it and maintain it.
