### ISSUE TITLE
Commandline parsing fails to produce errors

### ISSUE THREAD

**Issue by zander** [bitcoinclassic/bitcoinclassic#172]
Almost all professional software on unix uses a similar user interface when it comes to the commandline.

All of the executables that bitcoinclassic ships, however, do their own thing.  This works Ok for most cases, but many of the common user errors are not detected and will not be reported. Causing the usability of the software to be lower.

Specifically;
- when a user passes in an argument that doesn't exist, no warning is give. For instance if a user types '-deamon' instead of '-daemon', the argument is ignored and nothing is reported to the user.
- required arguments are not required.  
  for instance when you use the argument `-rpcuser=<user>` and you pass in `--rpcuser` without any arguments, no complaints are generated.

I suggest checking for command line parsing libraries like `getopt`.

**Comment by ftrader** [comment]
There is also the case of silent conversions of option values in not-so-expected ways.

Try specifying an integer argument as a hex value ... this would be very useful for version.
The number parsing on UNIX could auto-detect the base-16, but it's hardcoded not to, seemingly because intelligent string to number conversion is not available in the Windows platform's libraries.
What happens when one specifies 0x1234 ? It gets silently converted to 0. Nice.

/rant

**Comment by zander** [comment]
I would support the complete drop of the feature of command line options on Windows. Maybe just the standard 'version' and others that make the tool quit immediately after, but no more.
They can still do everything they want in the config file.

What I expect is that there is some code that describes all the command line options and stores them in some commandlineparser class. It does the checking and it does the printing of the options.
Then you use an instance of that class to get your data out.

There are tons out there, this is one I have experience with for the idea.
https://doc.qt.io/qt-5/qcommandlineparser.html

Maybe there is a good one in boost (since we probably don't want to pull in the qtcore library ;)
