### ISSUE TITLE
On linux try a different malloc

### ISSUE THREAD

**Issue by zander** [bitcoinclassic/bitcoinclassic#181]
Tests have shown that a mining node slowly will run out of memory. The test results showed that there was no memory-leak in the code, however.
The repeated calling of getblocktemplate (via the RPC interface) had the effect that malloc was called and the libc malloc implementation caused fragmentation. Which, in short, means that a large amount of memory stopped being available as a one-continues-block.

The suggestion is to make Bitcoin Classic work with a different malloc implementation. For instances JEMalloc.

**Comment by jtoomim** [comment]
This does not appear to still be an issue with the rewritten CreateNewBlock code added by morcos in 0.12, as that version of CNB does not do UTXO lookups in CNB any longer. It was the transaction verification and UTXO lookups that were causing memory allocation inside CNB, which in turn caused the memory fragmentation and increasing memory usage over time due to glibc's one-heap-per-thread design. I suggest closing this issue.

Edit: I'm seeing 655 MB of RSS on a node running 1.1 used for mining for a couple weeks without a restart.

**Comment by zander** [comment]
ok
