### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by infertux** [bitcoinclassic/bitcoinclassic#216]
I'm trying to figure out if there is any kind of automated build setup for Bitcoin Classic? Are those tests supposed to pass? `qa/pull-tester/rpc-tests.py -extended`

I'm getting failing tests locally (e.g. `Assertion failed: Test failed at test 32`) and similar issues on [Travis CI](https://travis-ci.org/infertux/bitcoinclassic/builds/193400996).

This stems from [this conversation](https://github.com/error10/bitcoin-dist/issues/25) where the apparent lack of proper tests is quite concerning, rightly so IMHO, especially for that kind of software. Did I miss anything?

**Comment by jamoes** [comment]
There are unit tests as well, located in the `src/test` directory (and `src/qt/test`). After building, you can run these tests by running the executable `src/test/test_bitcoin` (and `src/qt/test/test_bitcoin-qt`).

From looking at the Travis CI report you linked to, [the first test case](https://travis-ci.org/infertux/bitcoinclassic/builds/193400996) looks like it might be using Bitcoin Core's config against Bitcoin Classic's tests. It is referencing a file (`contrib/devtools/check-doc.py`), which exists in the Core codebase, but not the Classic codebase. I'm not able to replicate the errors I see in the other test cases.

I just ran the (non-extended) regression test suite on my machine (`qa/pull-tester/rpc-tests.py`), and had all tests pass for me. I also ran all unit tests, and they all passed as well.

However, when running the extended test suite (`qa/pull-tester/rpc-tests.py -extended`), I am seeing an error in the `maxuploadtarget.py` test. It looks like that failure is due to an error in the test itself. I've submitted a pull request to fix it: #218.

**Comment by infertux** [comment]
Thank you for the reply, that is great to hear.

`./src/test/test_bitcoin` is passing for me but `./qa/pull-tester/rpc-tests.py` is failing with `Assertion failed: Test failed at test 32`.

Would you be interested in a PR with a proper `.travis.yml` config (or any other CI service you might prefer)? I reckon having an automated testsuite would make the project a lot more legit ;)

**Comment by jamoes** [comment]
I can't seem to replicate the `Test failed at test 32` error you're seeing. Based on the Travis CI output from earlier, it looks like this test is from `qa/rpc-tests/bip68-112-113-p2p.py`, line 445. I have tried on both the 1.2 branch, and the master branch, and the tests all pass for me. Can you provide any more details that could help replicate the failing test?

I think setting up continuous integration is a great idea. It looks like there used to be a `.travis.yml` file, but it has since been removed. @zander may have more input here.

**Comment by zander** [comment]
> I'm trying to figure out if there is any kind of automated build setup for Bitcoin Classic? Are those tests supposed to pass? qa/pull-tester/rpc-tests.py -extended

Sounds like you found them!

Additionally there are the unit tests that jamoes pointed out to you.

Please see for more info; https://zander.github.io/posts/ClassicQuality/#Continues_Integration_building

**Comment by infertux** [comment]
@jamoes There isn't many details in the output (running `qa/pull-tester/rpc-tests.py -extended` in the `1.2` branch):

```
[...]
Test 29: PASS [580]
Test 30: PASS [581]
Test 31: PASS [582]
Assertion failed: Test failed at test 32
  File "/home/infertux/dev/bitcoinclassic/qa/rpc-tests/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/infertux/dev/bitcoinclassic/qa/rpc-tests/bip68-112-113-p2p.py", line 110, in run_test
    test.run()
  File "/home/infertux/dev/bitcoinclassic/qa/rpc-tests/test_framework/comptool.py", line 366, in run
    raise AssertionError("Test failed at test %d" % test_number)
Stopping nodes
Cleaning up
Failed
```

---

@zander Good point regarding Travis slowness and secure offline builds. However I think having a public CI somewhere would be beneficial. It would show what is actually being tested but more importantly it would make Bitcoin Classic look more solid regarding quality. For instance, `maxuploadtarget.py` was broken like @jamoes pointed out and who knows since when or what caused it. This hinders the project as people [won't package](https://github.com/error10/bitcoin-dist/issues/25) or distribute it assuming it's untested software. That said, I do appreciate your work so thank you for that :)

**Comment by zander** [comment]
The -extended part has some tests that are known to have issues. For instance there is one that can take 2 hours to run and use several gigabytes on disk. What that means is that failures there are often not the fault of bad code.

Ideally they still pass, I agree. I'll add an extra weekly or nightly run the CI system for this.
