### ISSUE TITLE
2 of 3 Multisig rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))

### ISSUE THREAD

**Issue by coinables** [bitcoinclassic/bitcoinclassic#284]
When creating a raw multisig in the console with Bitcoin Classic, after signing with both keys getting success: true, try to broadcast `rejected by network rules. (16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation))`

Seems to be related to https://github.com/fyookball/electrum/issues/6

**Comment by dgenr8** [comment]
I believe Classic needs https://github.com/bitcoinxt/bitcoinxt/pull/237/commits/c8f83168816f0574eeba3118e20377011d967602 and you also now need to specify an "amount" attribute with the multisig input(s) you are spending.

**Comment by coinables** [comment]
I just tried again with adding the `amount` parameter when signing. Still same error when trying to broadcast. An error occured:16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

**Comment by dgenr8** [comment]
Classic also needs the code changes to ``signrawtransaction`` I linked to.  If you need this right away, you could use ABC or XT which have the code, so you should only need to add the the "amount" attribute.

**Comment by coinables** [comment]
I've tried building and signing them in both ABC and Classic with the `amount` attribute and I'm still getting the same error.

**Comment by dgenr8** [comment]
As an example, ``"amount" : Decimal('2.20000000')`` (in python) should work. Set to the value of the multisig input.

**Comment by xorq** [comment]
Wow it worked !! Thanks ! so you have to put the exact right input value in the amount field...

**Comment by devilbond** [comment]
Hi there - Is there (or will there be) a new binary for OSX that incorporates the above changes?  I have my BCC stuck in Electron Cash and am unable to send because of this multisig problem.  I'm currently syncing the blockchain of Bitcoin Classic (UAHF version) and hope to import my address/s and *hopefully* send from there.  If there isn't a new binary, would you mind listing step by step what I would need to type into the console to be able to a) import my multisig address, b) send successfully.  I don't know any python, so it would be a copy/paste deal for me, so I really do need step-by-step instructions.  Sorry, I've just been trying to send my coins for a week now.

Thanks so much!

**Comment by xorq** [comment]
Could you get to the private keys of your multisig + the redeemscript ?
Then you should get bitcoin ABC client and should be easy from there...
you can pm me xorq@hotmail.com

**Comment by xorq** [comment]
in Bitcoin ABC's console follow this :

createrawtransaction '[{"txid":"TXID","vout":n}]' '{"OUTPUTADDRESS":6.9}'

***Raw TX***

signrawtransaction '***Raw TX***' '[{"txid":TXID,"vout":n, "amount": 1.234 , "scriptPubKey": scriptpubkey, "redeemScript":REDEEMSCRIPT}]' '["PKEY1","PKEY2", ...]'


So the way you redeem it is exactly the same as usual EXCEPT that you have to put the AMOUNT for each input in during the signrawtransaction call ... (the amounts have to be the same as the redeemed amounts)
Let me know if you got successful with this.

**Comment by coinables** [comment]
xorq, did you have to wait for it to sync fully for it to work?

**Comment by coinables** [comment]
Ok I finally got it in the ABC console. Different than I'm used to with core. As xorq stated, when signing there must be an amount parameter, and that amount must be for the ENTIRE input value. Even if you are spending less (change, miner fee) the amount parameter should represent the full value of the input being spent.

**Comment by devilbond** [comment]
@xorq Thanks man.  PM’d you.

**Comment by xorq** [comment]
I think you have to wait for your input to be synchronized for the broadcasting part, but you could also push it with any other tool like electron cash or viabtc push service

**Comment by zander** [comment]
If anyone could test this using the 1.3.4 release, that would be wonderful :)

**Comment by rromanchuk** [comment]
Getting the same issue with ABC, related to this https://bitcointalk.org/index.php?topic=1680640.0   pushing the tx with https://pool.viabtc.com/tools/BCC/broadcast/ and QT gives mew 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

Going to try with classic now.

**Comment by zander** [comment]
@rromanchuk a quickl look at your bitcointalk post shows you may be mixing address-types. Regtest addresses are not compatible with mainnet addresses.
I suggest starting classic in regtest and calling (via bitcoin-cli) the `createaddress` command which creates a proper address. Notice you need to do a `importprivkey` if you want to sign with it, but as a change-address you should be Ok.

ps. your issue seems to be quite unrelated to this task, though.

**Comment by coolmagic** [comment]
I can confirm as well that this error os resolved by defining exact amount in INPUT
