### ISSUE TITLE
Can not run bitcoind or bitcoin-qt due to bad config, unknown what config it is using

### ISSUE THREAD

**Issue by DaSpawn** [bitcoinclassic/bitcoinclassic#296]
I unfortunately can not find any information on where the config files are stored now.  I had a bad line in my old config that I removed but it is not using that config.  when I run wither app all I get is 

Error reading configuration file: unrecognized option

but it does not tell me in what file.  I even tried to use -choosedatadir option and that dialog does not tell me the folder either, it only says it already exists and to pick another

Could I suggest adding the config(s) used to the dialog(s)?

**Comment by zander** [comment]
The config file always comes from the datadir.

In Bitcoin Classic the 'uahf' edition uses the BitcoinCash dir instead of the Bitcoin dir.
So for instance this means that you will find it under `$HOME/.local/share/BitcoinCash` on Linux
(or same path under XDG_DATA_HOME if your distro sets that).
or `$HOME/Library/Application Support/BitcoinCash` on Mac
or `C:\Users\Username\AppData\Roaming\BitcoinCash` in Windows

There should have been a dialog explaining how the migration copied the data, including the directories it used. My guess is that your config not being parseable was a situation that didn't get tested yet.

Hope this helps.

**Comment by DaSpawn** [comment]
Excellent, fixed it, thanks!  Should I leave this open for the unparsable config confusion?

**Comment by zander** [comment]
Sure, I'll try and reproduce it. If I fail, I'll close.

**Comment by cross** [comment]
nb, I think on the Mac, this datadir is stored in prefs, which before #301 may not have been different between clients.  I think.
