### ISSUE TITLE
Detect / support chainstate obfuscation

### ISSUE THREAD

**Issue by dgenr8** [bitcoinclassic/bitcoinclassic#51]
Apply backport #7259 from core.  Without this, users who are moving from core 0.12 to classic will get a failure on launch.  A reindex fixes it, but that is not obvious to the user.

**Comment by seusher** [comment]
Just so everyone has context, there is a great obfuscation conversation here: https://github.com/bitcoin/bitcoin/issues/4069

Basically, the chainstate database is stored in .sst (leveldb) database files, so if someone includes a virus signature in a transaction, virus scanners on Windows will flag the file as containing a virus. #7259 obfuscates the data in the chainstate so its less likely to contain a virus signature. This only needs to be done on the chainstate even though the same data is in the blockchain files because most antivirus software ignores files > 32MB, and blockchain files are pre-allocated 128MB files. 

If someone upgrades to 0.12 where obfuscation is enabled by default, when they install classic, they will have to reindex the blockchain to rebuild the chainstate.

I agree this needs to be brought into classic.

**Comment by zander** [comment]
Just want to add that I'm not a fan of total obfuscation, its a destructive tactic and this code affects much more than just the one platform where this may possibly sometimes be needed.

**Comment by seusher** [comment]
@zander: Are you defining 'total obfuscation' as blockchain obfuscation, or as just chainstate obfuscation? I don't think anyone wants to obfuscate the entire blockchain since we are lucky enough to have it stored in files that are larger than what virus scanners look at.

**Comment by zander** [comment]
Fixed in 0.12.0 release
